[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
etherscan-api-key = '7ZJD3H4BAQS3RA72RK7533F5S3PA1X8RFQ'
# See more config options https://github.com/gakonst/foundry/tree/master/config